//
// This file was automatically generated by wxrc, do not edit by hand.
//

#ifndef __resource_h__
#define __resource_h__
class PanelControls : public wxPanel {
protected:
 wxRadioBox* radioboxShaderType;
 wxRadioBox* radioboxShaderProfile;
 wxStaticText* m_staticText1;
 wxTextCtrl* textEntrypoint;
 wxNotebook* m_notebook1;
 wxPanel* m_panel1;
 wxCheckBox* optionCompileDebug;
 wxCheckBox* optionCompileSkipValidation;
 wxCheckBox* optionCompileSkipOptimization;
 wxCheckBox* optionCompilePartialPrecision;
 wxCheckBox* optionCompileForceVSSoftwareNoOpt;
 wxCheckBox* optionCompileForcePSSoftNoOpt;
 wxCheckBox* optionCompileNoPreshader;
 wxCheckBox* optionCompileEnableStrictness;
 wxCheckBox* optionCompileEnableBackwards;
 wxCheckBox* optionCompileIEEEStrictness;
 wxCheckBox* optionCompileWarningsAreErrors;
 wxCheckBox* optionCompileResourcesMayAlias;
 wxCheckBox* optionCompileEnableUnboundedDescriptorTables;
 wxCheckBox* optionCompileAllResourcesBound;
 wxPanel* m_panel2;
 wxRadioBox* radioboxFlowControl;
 wxRadioBox* radioboxPackMatrix;
 wxRadioBox* radioboxOptimization;
 wxPanel* m_panel3;
 wxCheckBox* chPerformStripping;
 wxCheckBox* optionStrippingReflectionData;
 wxCheckBox* optionStrippingDebugInfo;
 wxCheckBox* optionStrippingTestBlobs;
 wxPanel* m_panel4;
 wxCheckBox* optionDisassemblyEnableColorCodes;
 wxCheckBox* optionDisassemblyEnableDefaultValues;
 wxCheckBox* optionDisassemblyEnableInstructionNumbering;
 wxCheckBox* optionDisassemblyDisableDebugInfo;
 wxCheckBox* optionDisassemblyEnableInstructionOffset;
 wxCheckBox* optionDisassemblyInstructionOnly;
 wxCheckBox* optionDisassemblyPrintHexLiterals;
 wxPanel* m_panel5;
 wxCheckBox* optionPreprocess;
 wxStaticText* m_staticText2;
 wxComboBox* comboboxPresets;
 wxButton* btnSavePreset;
 wxButton* btnDeletePreset;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("PanelControls"), wxT("wxPanel"));
  radioboxShaderType = XRCCTRL(*this,"radioboxShaderType",wxRadioBox);
  radioboxShaderProfile = XRCCTRL(*this,"radioboxShaderProfile",wxRadioBox);
  m_staticText1 = XRCCTRL(*this,"m_staticText1",wxStaticText);
  textEntrypoint = XRCCTRL(*this,"textEntrypoint",wxTextCtrl);
  m_notebook1 = XRCCTRL(*this,"m_notebook1",wxNotebook);
  m_panel1 = XRCCTRL(*this,"m_panel1",wxPanel);
  optionCompileDebug = XRCCTRL(*this,"optionCompileDebug",wxCheckBox);
  optionCompileSkipValidation = XRCCTRL(*this,"optionCompileSkipValidation",wxCheckBox);
  optionCompileSkipOptimization = XRCCTRL(*this,"optionCompileSkipOptimization",wxCheckBox);
  optionCompilePartialPrecision = XRCCTRL(*this,"optionCompilePartialPrecision",wxCheckBox);
  optionCompileForceVSSoftwareNoOpt = XRCCTRL(*this,"optionCompileForceVSSoftwareNoOpt",wxCheckBox);
  optionCompileForcePSSoftNoOpt = XRCCTRL(*this,"optionCompileForcePSSoftNoOpt",wxCheckBox);
  optionCompileNoPreshader = XRCCTRL(*this,"optionCompileNoPreshader",wxCheckBox);
  optionCompileEnableStrictness = XRCCTRL(*this,"optionCompileEnableStrictness",wxCheckBox);
  optionCompileEnableBackwards = XRCCTRL(*this,"optionCompileEnableBackwards",wxCheckBox);
  optionCompileIEEEStrictness = XRCCTRL(*this,"optionCompileIEEEStrictness",wxCheckBox);
  optionCompileWarningsAreErrors = XRCCTRL(*this,"optionCompileWarningsAreErrors",wxCheckBox);
  optionCompileResourcesMayAlias = XRCCTRL(*this,"optionCompileResourcesMayAlias",wxCheckBox);
  optionCompileEnableUnboundedDescriptorTables = XRCCTRL(*this,"optionCompileEnableUnboundedDescriptorTables",wxCheckBox);
  optionCompileAllResourcesBound = XRCCTRL(*this,"optionCompileAllResourcesBound",wxCheckBox);
  m_panel2 = XRCCTRL(*this,"m_panel2",wxPanel);
  radioboxFlowControl = XRCCTRL(*this,"radioboxFlowControl",wxRadioBox);
  radioboxPackMatrix = XRCCTRL(*this,"radioboxPackMatrix",wxRadioBox);
  radioboxOptimization = XRCCTRL(*this,"radioboxOptimization",wxRadioBox);
  m_panel3 = XRCCTRL(*this,"m_panel3",wxPanel);
  chPerformStripping = XRCCTRL(*this,"chPerformStripping",wxCheckBox);
  optionStrippingReflectionData = XRCCTRL(*this,"optionStrippingReflectionData",wxCheckBox);
  optionStrippingDebugInfo = XRCCTRL(*this,"optionStrippingDebugInfo",wxCheckBox);
  optionStrippingTestBlobs = XRCCTRL(*this,"optionStrippingTestBlobs",wxCheckBox);
  m_panel4 = XRCCTRL(*this,"m_panel4",wxPanel);
  optionDisassemblyEnableColorCodes = XRCCTRL(*this,"optionDisassemblyEnableColorCodes",wxCheckBox);
  optionDisassemblyEnableDefaultValues = XRCCTRL(*this,"optionDisassemblyEnableDefaultValues",wxCheckBox);
  optionDisassemblyEnableInstructionNumbering = XRCCTRL(*this,"optionDisassemblyEnableInstructionNumbering",wxCheckBox);
  optionDisassemblyDisableDebugInfo = XRCCTRL(*this,"optionDisassemblyDisableDebugInfo",wxCheckBox);
  optionDisassemblyEnableInstructionOffset = XRCCTRL(*this,"optionDisassemblyEnableInstructionOffset",wxCheckBox);
  optionDisassemblyInstructionOnly = XRCCTRL(*this,"optionDisassemblyInstructionOnly",wxCheckBox);
  optionDisassemblyPrintHexLiterals = XRCCTRL(*this,"optionDisassemblyPrintHexLiterals",wxCheckBox);
  m_panel5 = XRCCTRL(*this,"m_panel5",wxPanel);
  optionPreprocess = XRCCTRL(*this,"optionPreprocess",wxCheckBox);
  m_staticText2 = XRCCTRL(*this,"m_staticText2",wxStaticText);
  comboboxPresets = XRCCTRL(*this,"comboboxPresets",wxComboBox);
  btnSavePreset = XRCCTRL(*this,"btnSavePreset",wxButton);
  btnDeletePreset = XRCCTRL(*this,"btnDeletePreset",wxButton);
 }
public:
PanelControls(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class nameDialog : public wxDialog {
protected:
 wxStaticText* m_staticText3;
 wxTextCtrl* editPresetName;
 wxButton* btnOK;
 wxButton* btnCancel;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("nameDialog"), wxT("wxDialog"));
  m_staticText3 = XRCCTRL(*this,"m_staticText3",wxStaticText);
  editPresetName = XRCCTRL(*this,"editPresetName",wxTextCtrl);
  btnOK = XRCCTRL(*this,"btnOK",wxButton);
  btnCancel = XRCCTRL(*this,"btnCancel",wxButton);
 }
public:
nameDialog(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};
class AboutDlg : public wxDialog {
protected:
 wxStaticBitmap* m_icon;
 wxStaticText* m_staticAppName;
 wxStaticText* m_staticVersion;
 wxStaticText* m_staticCopyright;
 wxHyperlinkCtrl* m_twitter;
 wxTextCtrl* m_staticLicense;
 wxButton* wxID_OK;

private:
 void InitWidgetsFromXRC(wxWindow *parent){
  wxXmlResource::Get()->LoadObject(this,parent,wxT("AboutDlg"), wxT("wxDialog"));
  m_icon = XRCCTRL(*this,"m_icon",wxStaticBitmap);
  m_staticAppName = XRCCTRL(*this,"m_staticAppName",wxStaticText);
  m_staticVersion = XRCCTRL(*this,"m_staticVersion",wxStaticText);
  m_staticCopyright = XRCCTRL(*this,"m_staticCopyright",wxStaticText);
  m_twitter = XRCCTRL(*this,"m_twitter",wxHyperlinkCtrl);
  m_staticLicense = XRCCTRL(*this,"m_staticLicense",wxTextCtrl);
  wxID_OK = XRCCTRL(*this,"wxID_OK",wxButton);
 }
public:
AboutDlg(wxWindow *parent=NULL){
  InitWidgetsFromXRC((wxWindow *)parent);
 }
};

void 
InitXmlResource();
#endif
